### ISSUE TITLE
Replace TracyAdapter with PsrToTracyLoggerAdapter

### ISSUE THREAD

**Issue by JanTvrdik** [contributte/monolog#6]
Tracy 2.6.0 ships with built-in `PsrToTracyLoggerAdapter` which can be used instead of `TracyAdapter`. The `TracyAdapter` is a modified copy of the built-in `PsrToTracyLoggerAdapter` which extends `Logger` instead of just implementing `ILogger`. This is problematic, because it means that while `Tracy\Debugger::log(...)` is logged by Tracy, invoking `Psr\Log\LoggerInterface::log(...)` is not.

The correct approach for people who want to keep the behavior of `Tracy\Logger` (i.e. generating bluescreens, sending mails and writing to log files on disk), is instead configure monolog to use `Tracy\Logger` as one of its handlers.

```yaml
monolog:
    channel:
        default:
            handlers:
                - Monolog\Handler\PsrHandler(
                    Tracy\Bridges\Psr\TracyToPsrLoggerAdapter(
                        Tracy\Logger(...)
                    )
                )
```

This will result in `Tracy\Logger` being used even when `Psr\Log\LoggerInterface::log(...)` is called.
